sonar.projectKey=dev-employee-platform
sonar.organization=saadnaanaiy
sonar.sources=backend/src,frontend/src
sonar.tests=backend/src/test,frontend/src/test
sonar.javascript.lcov.reportPaths=backend/coverage/lcov.info,frontend/coverage/lcov.info
sonar.test.inclusions=**/*.spec.ts,**/*.test.ts,**/*.spec.tsx,**/*.test.tsx
sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**
sonar.typescript.tsconfigPath=backend/tsconfig.json,frontend/tsconfig.json
sonar.sourceEncoding=UTF-8