apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: employee-platform
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Saadnaanaiy/cloud_project___1.git
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: employee-platform
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
      - PruneLast=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
  ignoreDifferences:
    - group: apps
      kind: Deployment
      jsonPointers:
        - /spec/replicas
    - group: apps
      kind: StatefulSet
      jsonPointers:
        - /spec/volumeClaimTemplates/0/apiVersion
        - /spec/volumeClaimTemplates/0/kind
        - /spec/volumeClaimTemplates/0/status
        - /spec/volumeClaimTemplates/0/metadata
    - group: ""
      kind: Secret
      jsonPointers:
        - /data
