apiVersion: cloud.google.com/v1
kind: BackendConfig
metadata:
  name: frontend-cdn-config
  namespace: employee-platform
spec:
  cdn:
    enabled: true
    cachePolicy:
      includeHost: true
      includeProtocol: true
      includeQueryString: true
