apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: gcp-secret-store
  namespace: employee-platform
spec:
  provider:
    gcpsm:
      projectID: cloudappproject-494314
      auth:
        workloadIdentity:
          clusterLocation: europe-west1
          clusterName: dev-cloud-native-employee-gke
          serviceAccountRef:
            name: external-secrets-sa
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: external-secrets-sa
  namespace: employee-platform
  annotations:
    iam.gke.io/gcp-service-account: external-secrets-sa@cloudappproject-494314.iam.gserviceaccount.com
