apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: mysql-secret
  namespace: employee-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: mysql-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: MYSQL_ROOT_PASSWORD
      remoteRef:
        key: MYSQL_ROOT_PASSWORD
    - secretKey: MYSQL_DATABASE
      remoteRef:
        key: MYSQL_DATABASE
      property: employee_db
    - secretKey: DB_USERNAME
      remoteRef:
        key: DB_USERNAME
      property: employee_user
    - secretKey: DB_PASSWORD
      remoteRef:
        key: DB_PASSWORD
    - secretKey: GCS_BACKUP_BUCKET
      remoteRef:
        key: GCS_BACKUP_BUCKET
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: backend-secret
  namespace: employee-platform
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: gcp-secret-store
    kind: SecretStore
  target:
    name: backend-secret
    creationPolicy: Owner
    deletionPolicy: Retain
  data:
    - secretKey: JWT_SECRET
      remoteRef:
        key: JWT_SECRET
    - secretKey: JWT_EXPIRES_IN
      remoteRef:
        key: JWT_EXPIRES_IN
      property: 7d
    - secretKey: TURNSTILE_SECRET_KEY
      remoteRef:
        key: TURNSTILE_SECRET_KEY
    - secretKey: DEFAULT_ADMIN_PASSWORD
      remoteRef:
        key: DEFAULT_ADMIN_PASSWORD
    - secretKey: DEFAULT_HR_PASSWORD
      remoteRef:
        key: DEFAULT_HR_PASSWORD
    - secretKey: DEFAULT_MANAGER_PASSWORD
      remoteRef:
        key: DEFAULT_MANAGER_PASSWORD
